import { Deal } from './types'

export const mockDeals: Deal[] = [
  {
    id: '1',
    productName: 'Industrial LED Lighting Equipment',
    quantity: 500,
    priceUSDC: 45000,
    supplier: 'Lumina Industries',
    supplierAddress: 'GB7X...',
    term: 60,
    status: 'awaiting_funding',
    createdAt: '2024-01-15',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'pending' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'pending' },
    ],
    pymeName: 'TechRetail MX',
    description: 'High-efficiency LED lighting for commercial warehouses',
    category: 'Electronics',
    yieldAPR: 12.5,
  },
  {
    id: '2',
    productName: 'Organic Coffee Beans (Premium)',
    quantity: 1000,
    priceUSDC: 28000,
    supplier: 'Café del Sur',
    supplierAddress: 'GA9F...',
    term: 45,
    status: 'funded',
    createdAt: '2024-01-10',
    fundedAt: '2024-01-12',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'completed', completedAt: '2024-01-14' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'pending' },
    ],
    pymeName: 'Coffee House Network',
    escrowAddress: 'GCSW4X...',
    investorAddress: 'GBLN2Y...',
    description: 'Premium organic coffee beans, direct from Colombian farms',
    category: 'Food & Beverage',
    yieldAPR: 10.8,
  },
  {
    id: '3',
    productName: 'Medical Supplies - Surgical Gloves',
    quantity: 2000,
    priceUSDC: 18500,
    supplier: 'MedSupply Global',
    supplierAddress: 'GD2K...',
    term: 30,
    status: 'awaiting_funding',
    createdAt: '2024-01-18',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'pending' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'pending' },
    ],
    pymeName: 'HealthCare Distributors',
    description: 'FDA-approved surgical gloves for medical facilities',
    category: 'Healthcare',
    yieldAPR: 15.2,
  },
  {
    id: '4',
    productName: 'Textile Fabrics (Cotton Blend)',
    quantity: 800,
    priceUSDC: 32000,
    supplier: 'Global Textiles Co.',
    supplierAddress: 'GFMN...',
    term: 90,
    status: 'in_progress',
    createdAt: '2023-12-20',
    fundedAt: '2023-12-22',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'completed', completedAt: '2024-01-05' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'pending' },
    ],
    pymeName: 'Fashion Forward SA',
    escrowAddress: 'GCBP5Z...',
    investorAddress: 'GA7M1X...',
    description: 'Premium cotton blend fabrics for apparel manufacturing',
    category: 'Textiles',
    yieldAPR: 11.5,
  },
  {
    id: '5',
    productName: 'Construction Materials - Cement',
    quantity: 300,
    priceUSDC: 52000,
    supplier: 'BuildRight Supplies',
    supplierAddress: 'GH8L...',
    term: 75,
    status: 'awaiting_funding',
    createdAt: '2024-01-20',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'pending' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'pending' },
    ],
    pymeName: 'Infrastructure Builders Inc',
    description: 'High-grade cement for commercial construction projects',
    category: 'Construction',
    yieldAPR: 13.8,
  },
  {
    id: '6',
    productName: 'Automotive Parts - Brake Systems',
    quantity: 400,
    priceUSDC: 38000,
    supplier: 'AutoTech Manufacturing',
    supplierAddress: 'GC4P...',
    term: 60,
    status: 'completed',
    createdAt: '2023-11-15',
    fundedAt: '2023-11-17',
    completedAt: '2024-01-10',
    milestones: [
      { id: 'm1', name: 'Shipment Confirmation', percentage: 50, status: 'completed', completedAt: '2023-11-25' },
      { id: 'm2', name: 'Delivery Confirmation', percentage: 50, status: 'completed', completedAt: '2024-01-10' },
    ],
    pymeName: 'Auto Parts Wholesale',
    escrowAddress: 'GDZR3M...',
    investorAddress: 'GBXK9L...',
    description: 'OEM-quality brake systems for vehicle maintenance',
    category: 'Automotive',
    yieldAPR: 12.0,
  },
]
